mapCancsP<-function(D){
  site=D$site
  #   histo2=D$histo2
  histo3=D$histo3
  cancer=rep("misc",dim(D)[1])  # use misc as other 
  cancer[(site==809)]="unknown"
  cancer[(site>=0)&(site<150)]="oral"
  cancer[(site>=150)&(site<=159)]="esophagus"
  cancer[(site>=160)&(site<=169)]="stomach"
  cancer[(site>=170)&(site<=179)]="intestine"
  cancer[(site>=180)&(site<=189)]="colon"
  cancer[(site>=190)&(site<=219)]="rectal"
  cancer[(site>=220)&(site<=229)]="liver"
  cancer[(site>=230)&(site<=239)]="gallBladder"
  cancer[(site>=240)&(site<=259)]="pancreas"
  cancer[(site>=260)&(site<=269)]="GI"
  cancer[(site>=300)&(site<=319)]="sinus"
  cancer[(site>=320)&(site<=329)]="larynx"
  cancer[(site>=330)&(site<=349)]="lung"
  cancer[(site>=370)&(site<=379)]="thymus"
  cancer[(site>=380)&(site<=399)]="pleura"
  cancer[(site>=400)&(site<=419)]="bone"
  cancer[(site>=420)&(site<=429)]="misc"   #450 heme end up in misc in who so call here too
  cancer[(site>=440)&(site<=449)]="skin" # melanoma is in here
  cancer[(site>=470)&(site<=479)]="soft"  # was nerves"
  cancer[(site>=480)&(site<=489)]="GI"  # was retro
  cancer[(site>=490)&(site<=499)]="soft"
  cancer[(site>=500)&(site<=509)]="breast"
  cancer[(site>=510)&(site<=529)]="femGen"
  cancer[(site>=530)&(site<=539)]="cervix"
  cancer[(site>=540)&(site<=549)]="uterus"
  cancer[(site>=560)&(site<=569)]="ovary"
  cancer[(site>=570)&(site<=589)]="femGen"
  cancer[(site>=600)&(site<=609)]="maleGen"
  cancer[site==619]="prostate"
  cancer[(site>=620)&(site<=629)]="testes"
  cancer[(site>=630)&(site<=639)]="maleGen"
  cancer[(site>=640)&(site<=659)]="renal"
  cancer[(site>=660)&(site<=689)]="bladder"
  cancer[(site>=690)&(site<=699)]="eye"
  cancer[(site>=700)&(site<=729)]="brain"
  cancer[site==739]="thyroid"
  cancer[(site>=740)&(site<=759)]="thymus"
  cancer[(site>=760)&(site<=809)]="misc"
  
# 
#   cancer[(site>=1710)&(site<=1719)]="HnN" # went to oral?
#   cancer[(site>=1720)&(site<=1729)]="melanoma"
#   cancer[site==1991]="otherMalig"
  
  # clean things with histO3 codes that trump the heme ICD9 codes above
  cancer[(histo3>=9590)&(histo3<9600)]="NHL" 
  # cancer[(histo3>=9650)&(histo3<9670)]="hodgkin" 
  cancer[(histo3>=9650)&(histo3<9670)]="HL" 
  cancer[(histo3>=9670)&(histo3<9730)]="NHL" 
  cancer[(histo3>=9730)&(histo3<9735)]="MM" 
  cancer[(histo3>=9735)&(histo3<9740)]="NHL" 
  cancer[(histo3>=9740)&(histo3<=9742)]="MPN" #"mastocytosis" 
  cancer[(histo3>=9743)&(histo3<9760)]="MPN" # assume histiocytosis is more like MPN than NHL
  #   cancer[(histo3==9751)]="MPN" #"LCH" lagerhan cell histiocytes are APCs = macrophage like, guessing MPN-like
  cancer[(histo3>=9760)&(histo3<=9770)]="MM"  # outside of below there are ~20 cases of these
  #   this cancer[(ICD9>=2730)&(ICD9<2739)]="globinemia" yielded 5080 cases of 9761 and 9762
  
  
  cancer[(histo3>=9800)&(histo3<9810)]="OL" # takes back 60 AMLs from ICD9 in 9808 and 9809
  cancer[histo3==9948]="OL"  # aggressive NK leukemia lumped in here
  #   cancer[(histo3==9812)|(histo3==9806)]="ALLba" #ALL with BCR-ABL (110 cases) 2010-12 + 12 mixed lineage 2011-12
  cancer[(histo3>=9810)&(histo3<9840)]="ALL" # take some OL back to ALL
  cancer[(histo3==9831)&(D$yrdx>2009)]="LGL" # 9831 is cleanly LGL only starting in 2010
  cancer[(histo3==9823)]="CLL" # pull out the CLLs
  # cancer[(histo3==9670)]="SLL" # SLL has different risk time course, so better not merge with CLL.
  cancer[(histo3==9670)]="CLL" #more 2nd SLL since earlier DX of CLL=> more likely SLL, so better to pool
  # Dutch study placed 9800 and 9820 also in CLL, but incidence age responses are clearly different.
  cancer[(histo3>=9840)&(histo3<9940)]="AML" # take some OL back to AML, includes next two lines
  #   cancer[(histo3==9910)]="AML" #AMKL 
  #   cancer[(histo3==9930)]="AML" #myeloid sarcoma (blasts forming tumor outside of marrow ... advanced AML)
  cancer[histo3%in%c(9863,9875)]="CML"  # take back CMLs
  cancer[(histo3==9866)]="APL" # andmake APL exclusive
  cancer[histo3%in%c(9865,9869,9871,9896,9897,9911)]="AMLti"  # AML by tranlocation or inversion
  #  t(6,9),inv(3),inv(16),t(8,21),t(9,11),t(1,22)
  cancer[(histo3>9979)&(histo3<9990)]="MDS" ##!!!!! tMDS=9987 got mapped in with tAML=9920 starting in 2010
  #   cancer[(histo3==9987)]="tMDS" ##!!! so we have to pull both out and correct for this
  #   cancer[(histo3==9920)]="tAML" 
  #   cancer[(histo3==9982)]="RARS" # take out to look for correlations with CLL via SF3B1 
  #   cancer[(histo3==9986)]="MDSdel5q" # take out to look for extra radiation induction (skip: confounded by tMDS)
  #9980=RA; 9981=nothing, 9983=RAEB, 9984=RAEB-T transformation (also stopped in 2010),9985=RCMD, 9989=NOS
  cancer[(histo3==9940)]="HCL"  #hairy cell leukemia was getting into NHL (note: HCL in 20's goes to 9591=NHL)
  cancer[(histo3==9945)]="CMML" 
#   cancer[(histo3==9960)]="MDS" #"CMPD" #this got remapped to mdsMPN = 9975 in 2010
#   cancer[(histo3==9975)]="MDS"  #"mdsMPN": guessing this is CMML-like, and more MDS-like than MPN-like
  cancer[(histo3==9960)]="MPN" #switch to MPN to keep MDS clean 
  cancer[(histo3==9975)]="MPN" #same here, better keep MDS clean
  cancer[(histo3==9946)]="MPN" #"jCMML" these come out of 205.1/CML
  cancer[(histo3==9950)]="MPN" #"PV"
  cancer[(histo3==9961)]="MPN" #"PMF"
  cancer[(histo3==9962)]="MPN" #"ET"
  cancer[(histo3==9963)]="MPN" #"CNL"
  cancer[(histo3==9964)]="MPN" #"CEL"
  cancer[(histo3>=9965)&(histo3<=9967)]="MPN" # GFR mutatants 
  cancer[(histo3>=9970)&(histo3<=9971)]="NHL" # ICD9 put it mostly there, so sweep stray 1s into it also. 
  cancer[(histo3==9876)]="MPN" #"aCML"
  cancer[histo3==9140]="KS" # overwrite mostly skin as Kaposi Sarcoma (KS)
  cancer[(D$seqnum>=60)&(D$seqnum<=88)]="benign" # 88 is benign but unknown sequence
  ## most of below fall into benign, and most started in 2004.
  ##  Bottomline: Bucket to remove since my codes don't handle such seqnums.
  ##  Complications of handling them include: if I map 60 to 0 and 61 to 1, trouble may come in one caseID havinf 2 seqnum=0 or 1
  ##  rows. I'll leave figuring out how to handle this to someone with real interests in brain tumors. 
  #   cancer[(histo3==9530)]="meningioma" #supposedly malignant, but seqnums >59 confuse this.
  # #   cancer[(histo3>=9531)&(histo3<=9539)]="meningioma" #benigns, mix in with mal or comment to pool with unknown
  #   cancer[(histo3==9560)]="schwannoma"
  #   cancer[(histo3==8272)]="pituitary"
  D$cancer=as.factor(cancer)
  D
}  

# [172] "    0 = \"C00.0-External upper lip\""                                                     
# [173] "    1 = \"C00.1-External lower lip\""                                                     
# [174] "    2 = \"C00.2-External lip, NOS\""                                                      
# [175] "    3 = \"C00.3-Mucosa of upper lip\""                                                    
# [176] "    4 = \"C00.4-Mucosa of lower lip\""                                                    
# [177] "    5 = \"C00.5-Mucosa of lip, NOS\""                                                     
# [178] "    6 = \"C00.6-Commissure of lip\""                                                      
# [179] "    8 = \"C00.8-Overlapping lesion of lip\""                                              
# [180] "    9 = \"C00.9-Lip, NOS\""                                                               
# [181] "    19 = \"C01.9-Base of tongue, NOS\""                                                   
# [182] "    20 = \"C02.0-Dorsal surface of tongue, NOS\""                                         
# [183] "    21 = \"C02.1-Border of tongue\""                                                      
# [184] "    22 = \"C02.2-Ventral surface of tongue, NOS\""                                        
# [185] "    23 = \"C02.3-Anterior 2/3 of tongue, NOS\""                                           
# [186] "    24 = \"C02.4-Lingual tonsil\""                                                        
# [187] "    28 = \"C02.8-Overlapping lesion of tongue\""                                          
# [188] "    29 = \"C02.9-Tongue, NOS\""                                                           
# [189] "    30 = \"C03.0-Upper gum\""                                                             
# [190] "    31 = \"C03.1-Lower gum\""                                                             
# [191] "    39 = \"C03.9-Gum, NOS\""                                                              
# [192] "    40 = \"C04.0-Anterior floor of mouth\""                                               
# [193] "    41 = \"C04.1-Lateral floor of mouth\""                                                
# [194] "    48 = \"C04.8-Overlapping lesion of floor of mouth\""                                  
# [195] "    49 = \"C04.9-Floor of mouth, NOS\""                                                   
# [196] "    50 = \"C05.0-Hard palate\""                                                           
# [197] "    51 = \"C05.1-Soft palate, NOS\""                                                      
# [198] "    52 = \"C05.2-Uvula\""                                                                 
# [199] "    58 = \"C05.8-Overlapping lesion of palate\""                                          
# [200] "    59 = \"C05.9-Palate, NOS\""                                                           
# [201] "    60 = \"C06.0-Cheek mucosa\""                                                          
# [202] "    61 = \"C06.1-Vestibule of mouth\""                                                    
# [203] "    62 = \"C06.2-Retromolar area\""                                                       
# [204] "    68 = \"C06.8-Overlapping lesion of other & unspecified mouth\""                       
# [205] "    69 = \"C06.9-Mouth, NOS\""                                                            
# [206] "    79 = \"C07.9-Parotid gland\""                                                         
# [207] "    80 = \"C08.0-Submandibular gland\""                                                   
# [208] "    81 = \"C08.1-Sublingual gland\""                                                      
# [209] "    88 = \"C08.8-Overlapping lesion of major salivary glands\""                           
# [210] "    89 = \"C08.9-Major salivary gland, NOS\""                                             
# [211] "    90 = \"C09.0-Tonsillar fossa\""                                                       
# [212] "    91 = \"C09.1-Tonsillar pillar\""                                                      
# [213] "    98 = \"C09.8-Overlapping lesion of tonsil\""                                          
# [214] "    99 = \"C09.9-Tonsil, NOS\""                                                           
# [215] "    100 = \"C10.0-Vallecula\""                                                            
# [216] "    101 = \"C10.1-Anterior surface of epiglottis\""                                       
# [217] "    102 = \"C10.2-Lateral wall of oropharynx\""                                           
# [218] "    103 = \"C10.3-Posterior wall of oropharynx\""                                         
# [219] "    104 = \"C10.4-Branchial cleft\""                                                      
# [220] "    108 = \"C10.8-Overlapping lesion of oropharynx\""                                     
# [221] "    109 = \"C10.9-Oropharynx, NOS\""                                                      
# [222] "    110 = \"C11.0-Superior wall of nasopharynx\""                                         
# [223] "    111 = \"C11.1-Posterior wall of nasopharynx\""                                        
# [224] "    112 = \"C11.2-Lateral wall of nasopharynx\""                                          
# [225] "    113 = \"C11.3-Anterior wall of nasopharynx\""                                         
# [226] "    118 = \"C11.8-Overlapping lesion of nasopharynx\""                                    
# [227] "    119 = \"C11.9-Nasopharynx, NOS\""                                                     
# [228] "    129 = \"C12.9-Pyriform sinus\""                                                       
# [229] "    130 = \"C13.0-Postcricoid region\""                                                   
# [230] "    131 = \"C13.1-Aryepiglottic fold, hypopharyngeal\""                                   
# [231] "    132 = \"C13.2-Posterior wall of hypopharynx\""                                        
# [232] "    138 = \"C13.8-Overlapping lesion of hypopharynx\""                                    
# [233] "    139 = \"C13.9-Hypopharynx, NOS\""                                                     
# [234] "    140 = \"C14.0-Pharynx, NOS\""                                                         
# [235] "    142 = \"C14.2-Waldeyers ring\""                                                       
# [236] "    148 = \"C14.8-Overlapping lesion of lip, oral cavity & pharynx\""                     
# [237] "    150 = \"C15.0-Cervical esophagus\""                                                   
# [238] "    151 = \"C15.1-Thoracic esophagus\""                                                   
# [239] "    152 = \"C15.2-Abdominal esophagus\""                                                  
# [240] "    153 = \"C15.3-Upper third of esophagus\""                                             
# [241] "    154 = \"C15.4-Middle third of esophagus\""                                            
# [242] "    155 = \"C15.5-Lower third of esophagus\""                                             
# [243] "    158 = \"C15.8-Overlapping lesion of esophagus\""                                      
# [244] "    159 = \"C15.9-Esophagus, NOS\""                                                       
# [245] "    160 = \"C16.0-Cardia, NOS\""                                                          
# [246] "    161 = \"C16.1-Fundus of stomach\""                                                    
# [247] "    162 = \"C16.2-Body of stomach\""                                                      
# [248] "    163 = \"C16.3-Gastric antrum\""                                                       
# [249] "    164 = \"C16.4-Pylorus\""                                                              
# [250] "    165 = \"C16.5-Lesser curvature of stomach NOS\""                                      
# [251] "    166 = \"C16.6-Greater curvature of stomach NOS\""                                     
# [252] "    168 = \"C16.8-Overlapping lesion of stomach\""                                        
# [253] "    169 = \"C16.9-Stomach, NOS\""                                                         
# [254] "    170 = \"C17.0-Duodenum\""                                                             
# [255] "    171 = \"C17.1-Jejunum\""                                                              
# [256] "    172 = \"C17.2-Ileum\""                                                                
# [257] "    173 = \"C17.3-Meckels diverticulum\""                                                 
# [258] "    178 = \"C17.8-Overlapping lesion of small intestine\""                                
# [259] "    179 = \"C17.9-Small intestine, NOS\""                                                 
# [260] "    180 = \"C18.0-Cecum\""                                                                
# [261] "    181 = \"C18.1-Appendix\""                                                             
# [262] "    182 = \"C18.2-Ascending colon\""                                                      
# [263] "    183 = \"C18.3-Hepatic flexure of colon\""                                             
# [264] "    184 = \"C18.4-Transverse colon\""                                                     
# [265] "    185 = \"C18.5-Splenic flexure of colon\""                                             
# [266] "    186 = \"C18.6-Descending colon\""                                                     
# [267] "    187 = \"C18.7-Sigmoid colon\""                                                        
# [268] "    188 = \"C18.8-Overlapping lesion of colon\""                                          
# [269] "    189 = \"C18.9-Colon, NOS\""                                                           
# [270] "    199 = \"C19.9-Rectosigmoid junction\""                                                
# [271] "    209 = \"C20.9-Rectum, NOS\""                                                          
# [272] "    210 = \"C21.0-Anus, NOS\""                                                            
# [273] "    211 = \"C21.1-Anal canal\""                                                           
# [274] "    212 = \"C21.2-Cloacogenic zone\""                                                     
# [275] "    218 = \"C21.8-Overlapping lesion of rectum, anus, and anal canal\""                   
# [276] "    220 = \"C22.0-Liver\""                                                                
# [277] "    221 = \"C22.1-Intrahepatic bile duct\""                                               
# [278] "    239 = \"C23.9-Gallbladder\""                                                          
# [279] "    240 = \"C24.0-Extrahepatic bile duct\""                                               
# [280] "    241 = \"C24.1-Ampulla of Vater\""                                                     
# [281] "    248 = \"C24.8-Overlapping lesion of biliary tract\""                                  
# [282] "    249 = \"C24.9-Biliary tract, NOS\""                                                   
# [283] "    250 = \"C25.0-Head of pancreas\""                                                     
# [284] "    251 = \"C25.1-Body of pancreas\""                                                     
# [285] "    252 = \"C25.2-Tail of pancreas\""                                                     
# [286] "    253 = \"C25.3-Pancreatic duct\""                                                      
# [287] "    254 = \"C25.4-Islets of Langerhans\""                                                 
# [288] "    257 = \"C25.7-Other specified parts of pancreas\""                                    
# [289] "    258 = \"C25.8-Overlapping lesion of pancreas\""                                       
# [290] "    259 = \"C25.9-Pancreas, NOS\""                                                        
# [291] "    260 = \"C26.0-Intestinal tract, NOS\""                                                
# [292] "    268 = \"C26.8-Overlapping lesion of digestive system\""                               
# [293] "    269 = \"C26.9-Gastrointestinal tract, NOS\""                                          
# [294] "    300 = \"C30.0-Nasal cavity\""                                                         
# [295] "    301 = \"C30.1-Middle ear\""                                                           
# [296] "    310 = \"C31.0-Maxillary sinus\""                                                      
# [297] "    311 = \"C31.1-Ethmoid sinus\""                                                        
# [298] "    312 = \"C31.2-Frontal sinus\""                                                        
# [299] "    313 = \"C31.3-Sphenoid sinus\""                                                       
# [300] "    318 = \"C31.8-Overlapping lesion of accessory sinuses\""                              
# [301] "    319 = \"C31.9-Accessory sinus, NOS\""                                                 
# [302] "    320 = \"C32.0-Glottis\""                                                              
# [303] "    321 = \"C32.1-Supraglottis\""                                                         
# [304] "    322 = \"C32.2-Subglottis\""                                                           
# [305] "    323 = \"C32.3-Laryngeal cartilage\""                                                  
# [306] "    328 = \"C32.8-Overlapping lesion of larynx\""                                         
# [307] "    329 = \"C32.9-Larynx, NOS\""                                                          
# [308] "    339 = \"C33.9-Trachea\""                                                              
# [309] "    340 = \"C34.0-Main bronchus\""                                                        
# [310] "    341 = \"C34.1-Upper lobe, lung\""                                                     
# [311] "    342 = \"C34.2-Middle lobe, lung\""                                                    
# [312] "    343 = \"C34.3-Lower lobe, lung\""                                                     
# [313] "    348 = \"C34.8-Overlapping lesion of lung\""                                           
# [314] "    349 = \"C34.9-Lung, NOS\""                                                            
# [315] "    379 = \"C37.9-Thymus\""                                                               
# [316] "    380 = \"C38.0-Heart\""                                                                
# [317] "    381 = \"C38.1-Anterior mediastinum\""                                                 
# [318] "    382 = \"C38.2-Posterior mediastinum\""                                                
# [319] "    383 = \"C38.3-Mediastinum, NOS\""                                                     
# [320] "    384 = \"C38.4-Pleura, NOS\""                                                          
# [321] "    388 = \"C38.8-Overlapping lesion of heart, mediastinum and pleura\""                  
# [322] "    390 = \"C39.0-Upper respiratory tract, NOS\""                                         
# [323] "    398 = \"C39.8-Overlapping lesion of respiratory system\""                             
# [324] "    399 = \"C39.9-Ill-defined sites within respiratory system\""                          
# [325] "    400 = \"C40.0-Long bones: upper limb, scapula, and associated joints\""               
# [326] "    401 = \"C40.1-Short bones of upper limb and associated joints\""                      
# [327] "    402 = \"C40.2-Long bones of lower limb and associated joints\""                       
# [328] "    403 = \"C40.3-Short bones of lower limb and associated joints\""                      
# [329] "    408 = \"C40.8-Overlap of bones, joints, and art. cartilage of limbs\""                
# [330] "    409 = \"C40.9-Bone of limb, NOS\""                                                    
# [331] "    410 = \"C41.0-Bones of skull and face and associated joints\""                        
# [332] "    411 = \"C41.1-Mandible\""                                                             
# [333] "    412 = \"C41.2-Vertebral column\""                                                     
# [334] "    413 = \"C41.3-Rib, sternum, clavicle and associated joints\""                         
# [335] "    414 = \"C41.4-Pelvic bones, sacrum, coccyx and associated joints\""                   
# [336] "    418 = \"C41.8-Overlap bones, joints, and art. cartilage\""                            
# [337] "    419 = \"C41.9-Bone, NOS\""                                                            
# [338] "    420 = \"C42.0-Blood\""                                                                
# [339] "    421 = \"C42.1-Bone marrow\""                                                          
# [340] "    422 = \"C42.2-Spleen\""                                                               
# [341] "    423 = \"C42.3-Reticuloendothelial system, NOS\""                                      
# [342] "    424 = \"C42.4-Hematopoietic system, NOS\""                                            
# [343] "    440 = \"C44.0-Skin of lip, NOS\""                                                     
# [344] "    441 = \"C44.1-Eyelid\""                                                               
# [345] "    442 = \"C44.2-External ear\""                                                         
# [346] "    443 = \"C44.3-Skin other/unspec parts of face\""                                      
# [347] "    444 = \"C44.4-Skin of scalp and neck\""                                               
# [348] "    445 = \"C44.5-Skin of trunk\""                                                        
# [349] "    446 = \"C44.6-Skin of upper limb and shoulder\""                                      
# [350] "    447 = \"C44.7-Skin of lower limb and hip\""                                           
# [351] "    448 = \"C44.8-Overlapping lesion of skin\""                                           
# [352] "    449 = \"C44.9-Skin, NOS\""                                                            
# [353] "    470 = \"C47.0-Periph nerves & autonomic nerv sys: head, face, neck\""                 
# [354] "    471 = \"C47.1-Periph nerves & autonomic nerv sys: upr limb, shoulder\""               
# [355] "    472 = \"C47.2-Periph nerves & autonomic nerv sys: lower limb, hip\""                  
# [356] "    473 = \"C47.3-Periph nerves & autonomic nerv sys: thorax\""                           
# [357] "    474 = \"C47.4-Periph nerves & autonomic nerv sys: abdomen\""                          
# [358] "    475 = \"C47.5-Periph nerves & autonomic nerv sys: pelvis\""                           
# [359] "    476 = \"C47.6-Periph nerves & autonomic nerv sys: trunk, NOS\""                       
# [360] "    478 = \"C47.8-Overlap of peripheral nerves and autonomic nerv sys\""                  
# [361] "    479 = \"C47.9-Autonomic nervous system, NOS\""                                        
# [362] "    480 = \"C48.0-Retroperitoneum\""                                                      
# [363] "    481 = \"C48.1-Specified parts of peritoneum\""                                        
# [364] "    482 = \"C48.2-Peritoneum, NOS\""                                                      
# [365] "    488 = \"C48.8-Overlapping lesion of retroperitoneum & peritoneum\""                   
# [366] "    490 = \"C49.0-Conn, subcutaneous, other soft tis: head, face, neck\""                 
# [367] "    491 = \"C49.1-Conn, subcutaneous, other soft tis: upr limb, shoulder\""               
# [368] "    492 = \"C49.2-Conn, subcutaneous, other soft tis: lower limb, hip\""                  
# [369] "    493 = \"C49.3-Conn, subcutaneous, other soft tis: thorax\""                           
# [370] "    494 = \"C49.4-Conn, subcutaneous, other soft tis: abdomen\""                          
# [371] "    495 = \"C49.5-Conn, subcutaneous, other soft tis: pelvis\""                           
# [372] "    496 = \"C49.6-Conn, subcutaneous, other soft tis: trunk, NOS\""                       
# [373] "    498 = \"C49.8-Overlap conn, subcutaneous, and other soft tissues\""                   
# [374] "    499 = \"C49.9-Conn, subcutaneous and other soft tissues, NOS\""                       
# [375] "    500 = \"C50.0-Nipple\""                                                               
# [376] "    501 = \"C50.1-Central portion of breast\""                                            
# [377] "    502 = \"C50.2-Upper-inner quadrant of breast\""                                       
# [378] "    503 = \"C50.3-Lower-inner quadrant of breast\""                                       
# [379] "    504 = \"C50.4-Upper-outer quadrant of breast\""                                       
# [380] "    505 = \"C50.5-Lower-outer quadrant of breast\""                                       
# [381] "    506 = \"C50.6-Axillary tail of breast\""                                              
# [382] "    508 = \"C50.8-Overlapping lesion of breast\""                                         
# [383] "    509 = \"C50.9-Breast, NOS\""                                                          
# [384] "    510 = \"C51.0-Labium majus\""                                                         
# [385] "    511 = \"C51.1-Labium minus\""                                                         
# [386] "    512 = \"C51.2-Clitoris\""                                                             
# [387] "    518 = \"C51.8-Overlapping lesion of vulva\""                                          
# [388] "    519 = \"C51.9-Vulva, NOS\""                                                           
# [389] "    529 = \"C52.9-Vagina, NOS\""                                                          
# [390] "    530 = \"C53.0-Endocervix\""                                                           
# [391] "    531 = \"C53.1-Exocervix\""                                                            
# [392] "    538 = \"C53.8-Overlapping lesion of cervix uteri\""                                   
# [393] "    539 = \"C53.9-Cervix uteri\""                                                         
# [394] "    540 = \"C54.0-Isthmus uteri\""                                                        
# [395] "    541 = \"C54.1-Endometrium\""                                                          
# [396] "    542 = \"C54.2-Myometrium\""                                                           
# [397] "    543 = \"C54.3-Fundus uteri\""                                                         
# [398] "    548 = \"C54.8-Overlapping lesion of corpus uteri\""                                   
# [399] "    549 = \"C54.9-Corpus uteri\""                                                         
# [400] "    559 = \"C55.9-Uterus, NOS\""                                                          
# [401] "    569 = \"C56.9-Ovary\""                                                                
# [402] "    570 = \"C57.0-Fallopian tube\""                                                       
# [403] "    571 = \"C57.1-Broad ligament\""                                                       
# [404] "    572 = \"C57.2-Round ligament\""                                                       
# [405] "    573 = \"C57.3-Parametrium\""                                                          
# [406] "    574 = \"C57.4-Uterine adnexa\""                                                       
# [407] "    577 = \"C57.7-Other specified parts of female genital organs\""                       
# [408] "    578 = \"C57.8-Overlapping lesion of female genital organs\""                          
# [409] "    579 = \"C57.9-Female genital tract, NOS\""                                            
# [410] "    589 = \"C58.9-Placenta\""                                                             
# [411] "    600 = \"C60.0-Prepuce\""                                                              
# [412] "    601 = \"C60.1-Glans penis\""                                                          
# [413] "    602 = \"C60.2-Body of penis\""                                                        
# [414] "    608 = \"C60.8-Overlapping lesion of penis\""                                          
# [415] "    609 = \"C60.9-Penis, NOS\""                                                           
# [416] "    619 = \"C61.9-Prostate gland\""                                                       
# [417] "    620 = \"C62.0-Undescended testis\""                                                   
# [418] "    621 = \"C62.1-Descended testis\""                                                     
# [419] "    629 = \"C62.9-Testis, NOS\""                                                          
# [420] "    630 = \"C63.0-Epididymis\""                                                           
# [421] "    631 = \"C63.1-Spermatic cord\""                                                       
# [422] "    632 = \"C63.2-Scrotum, NOS\""                                                         
# [423] "    637 = \"C63.7-Other specified parts of male genital organs\""                         
# [424] "    638 = \"C63.8-Overlapping lesion of male genital organs\""                            
# [425] "    639 = \"C63.9-Male genital organs, NOS\""                                             
# [426] "    649 = \"C64.9-Kidney, NOS\""                                                          
# [427] "    659 = \"C65.9-Renal pelvis\""                                                         
# [428] "    669 = \"C66.9-Ureter\""                                                               
# [429] "    670 = \"C67.0-Trigone of bladder\""                                                   
# [430] "    671 = \"C67.1-Dome of bladder\""                                                      
# [431] "    672 = \"C67.2-Lateral wall of bladder\""                                              
# [432] "    673 = \"C67.3-Anterior wall of bladder\""                                             
# [433] "    674 = \"C67.4-Posterior wall of bladder\""                                            
# [434] "    675 = \"C67.5-Bladder neck\""                                                         
# [435] "    676 = \"C67.6-Ureteric orifice\""                                                     
# [436] "    677 = \"C67.7-Urachus\""                                                              
# [437] "    678 = \"C67.8-Overlapping lesion of bladder\""                                        
# [438] "    679 = \"C67.9-Bladder, NOS\""                                                         
# [439] "    680 = \"C68.0-Urethra\""                                                              
# [440] "    681 = \"C68.1-Paraurethral gland\""                                                   
# [441] "    688 = \"C68.8-Overlapping lesion of urinary organs\""                                 
# [442] "    689 = \"C68.9-Urinary system, NOS\""                                                  
# [443] "    690 = \"C69.0-Conjunctiva\""                                                          
# [444] "    691 = \"C69.1-Cornea, NOS\""                                                          
# [445] "    692 = \"C69.2-Retina\""                                                               
# [446] "    693 = \"C69.3-Choroid\""                                                              
# [447] "    694 = \"C69.4-Ciliary body\""                                                         
# [448] "    695 = \"C69.5-Lacrimal gland\""                                                       
# [449] "    696 = \"C69.6-Orbit, NOS\""                                                           
# [450] "    698 = \"C69.8-Overlapping lesion of eye and adnexa\""                                 
# [451] "    699 = \"C69.9-Eye, NOS\""                                                             
# [452] "    700 = \"C70.0-Cerebral meninges\""                                                    
# [453] "    701 = \"C70.1-Spinal meninges\""                                                      
# [454] "    709 = \"C70.9-Meninges, NOS\""                                                        
# [455] "    710 = \"C71.0-Cerebrum\""                                                             
# [456] "    711 = \"C71.1-Frontal lobe\""                                                         
# [457] "    712 = \"C71.2-Temporal lobe\""                                                        
# [458] "    713 = \"C71.3-Parietal lobe\""                                                        
# [459] "    714 = \"C71.4-Occipital lobe\""                                                       
# [460] "    715 = \"C71.5-Ventricle, NOS\""                                                       
# [461] "    716 = \"C71.6-Cerebellum, NOS\""                                                      
# [462] "    717 = \"C71.7-Brain stem\""                                                           
# [463] "    718 = \"C71.8-Overlapping lesion of brain\""                                          
# [464] "    719 = \"C71.9-Brain, NOS\""                                                           
# [465] "    720 = \"C72.0-Spinal cord\""                                                          
# [466] "    721 = \"C72.1-Cauda equina\""                                                         
# [467] "    722 = \"C72.2-Olfactory nerve\""                                                      
# [468] "    723 = \"C72.3-Optic nerve\""                                                          
# [469] "    724 = \"C72.4-Acoustic nerve\""                                                       
# [470] "    725 = \"C72.5-Cranial nerve, NOS\""                                                   
# [471] "    728 = \"C72.8-Overlapping lesion of brain & CNS\""                                    
# [472] "    729 = \"C72.9-Nervous system, NOS\""                                                  
# [473] "    739 = \"C73.9-Thyroid gland\""                                                        
# [474] "    740 = \"C74.0-Cortex of adrenal gland\""                                              
# [475] "    741 = \"C74.1-Medulla of adrenal gland\""                                             
# [476] "    749 = \"C74.9-Adrenal gland, NOS\""                                                   
# [477] "    750 = \"C75.0-Parathyroid gland\""                                                    
# [478] "    751 = \"C75.1-Pituitary gland\""                                                      
# [479] "    752 = \"C75.2-Craniopharyngeal duct\""                                                
# [480] "    753 = \"C75.3-Pineal gland\""                                                         
# [481] "    754 = \"C75.4-Carotid body\""                                                         
# [482] "    755 = \"C75.5-Aortic body & other paraganglia\""                                      
# [483] "    758 = \"C75.8-Overlapping lesion of endocrine glands\""                               
# [484] "    759 = \"C75.9-Endocrine gland, NOS\""                                                 
# [485] "    760 = \"C76.0-Head, face or neck, NOS\""                                              
# [486] "    761 = \"C76.1-Thorax, NOS\""                                                          
# [487] "    762 = \"C76.2-Abdomen, NOS\""                                                         
# [488] "    763 = \"C76.3-Pelvis, NOS\""                                                          
# [489] "    764 = \"C76.4-Upper limb, NOS\""                                                      
# [490] "    765 = \"C76.5-Lower limb, NOS\""                                                      
# [491] "    767 = \"C76.7-Other ill-defined sites\""                                              
# [492] "    768 = \"C76.8-Overlapping lesion of ill-defined sites\""                              
# [493] "    770 = \"C77.0-Lymph nodes of head, face & neck\""                                     
# [494] "    771 = \"C77.1-Intrathoracic lymph nodes\""                                            
# [495] "    772 = \"C77.2-Intra-abdominal lymph nodes\""                                          
# [496] "    773 = \"C77.3-Lymph nodes of axilla or arm\""                                         
# [497] "    774 = \"C77.4-Lymph nodes of inguinal region or leg\""                                
# [498] "    775 = \"C77.5-Pelvic lymph nodes\""                                                   
# [499] "    778 = \"C77.8-Lymph nodes of multiple regions\""                                      
# [500] "    779 = \"C77.9-Lymph node, NOS\""                                                      
# [501] "    809 = \"C80.9-Unknown primary site\""                                                 
# [502] "    ;"   