// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fillPYM
NumericMatrix fillPYM(SEXP PY, SEXP PYM);
RcppExport SEXP SEERaBomb_fillPYM(SEXP PYSEXP, SEXP PYMSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type PY(PYSEXP );
        Rcpp::traits::input_parameter< SEXP >::type PYM(PYMSEXP );
        NumericMatrix __result = fillPYM(PY, PYM);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
